package fi.tuni.tamk.tiko.bmb.blogbackend.model;

public class LoremIpsum {
    public static String loremIpsum = "\n" +
            "\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas maximus lacinia sagittis. Aliquam non rutrum sapien. Vestibulum aliquet nulla in felis semper porttitor. Quisque fermentum eleifend urna, sagittis convallis quam cursus aliquet. Etiam nec nibh vel velit lobortis auctor. Pellentesque vehicula tortor quis purus auctor, eu dignissim dui vulputate. In tincidunt nisl ac massa varius fringilla. Maecenas pulvinar metus congue, viverra massa a, ornare elit. Maecenas viverra orci non ultrices rutrum. Etiam commodo non elit in ultricies. Vestibulum quis iaculis enim, id posuere lorem. Sed justo nisi, commodo sit amet tincidunt non, commodo sit amet quam. Morbi nec vehicula purus, eu vestibulum neque. Duis iaculis, felis eu finibus maximus, erat lorem convallis purus, fringilla vehicula erat nisi ut erat. Donec in felis at erat lacinia venenatis. Phasellus malesuada ante quis iaculis accumsan.\n" +
            "\n" +
            "Integer aliquam nunc quis ex dignissim, at tincidunt ipsum feugiat. Fusce dolor leo, ultrices vel tempus eget, blandit ac justo. Aenean molestie fermentum nulla, eu suscipit ipsum consectetur nec. Nulla tempor efficitur pulvinar. Praesent facilisis imperdiet enim at rutrum. Mauris rutrum nec massa vitae pulvinar. Pellentesque fermentum quam dui, a vestibulum odio scelerisque id. Suspendisse potenti. Vivamus imperdiet vestibulum quam nec tincidunt. Nulla a mollis libero, quis ornare magna. Aenean gravida aliquam tellus sed tincidunt. Suspendisse iaculis, dui eu dapibus lobortis, nisi purus tempor dolor, vel porttitor tortor neque ut nulla. Nam vehicula urna quis elit tincidunt, at consequat augue tristique. Mauris et eros sit amet magna feugiat mattis non et est. Vivamus sed fermentum diam, nec euismod lorem.\n" +
            "\n" +
            "Phasellus tincidunt porta ante, sed vulputate ligula rhoncus non. Donec in tristique nulla. Nulla pretium magna placerat leo pretium ultricies. Sed vulputate fermentum tortor vitae congue. Cras laoreet nulla vitae lacus sodales, eget pretium sem efficitur. Etiam cursus orci malesuada lacus vulputate, sit amet molestie risus molestie. In sit amet nulla commodo, condimentum turpis et, ultricies libero. Donec sed dolor vel elit ultricies pretium. Aenean commodo vehicula massa. Cras porta ipsum ut fringilla auctor. Nam placerat dapibus pharetra. Vivamus lobortis eu elit in rutrum.\n" +
            "\n" +
            "Curabitur tempor mauris ligula, eget tristique metus sagittis ac. Maecenas in tortor in dolor consectetur convallis. Morbi leo erat, posuere et est id, tincidunt fermentum tellus. Nulla facilisi. Duis dolor est, interdum eu mollis ut, vehicula id enim. Nulla sodales a neque nec cursus. Suspendisse ac est scelerisque, finibus lacus in, fermentum nisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet erat at risus egestas luctus. Mauris in sollicitudin sem, at venenatis velit. Sed non leo id tortor congue luctus et sed sem. Ut sed congue urna, quis laoreet nisl. In ligula tellus, fermentum vitae pellentesque vitae, interdum vel ligula. Quisque ac libero nisl.\n" +
            "\n" +
            "Morbi eget ullamcorper risus. Praesent a imperdiet felis. Morbi nunc turpis, pulvinar a ullamcorper eget, sodales nec sem. Morbi eget sem nisi. Duis bibendum ex velit, at mattis tellus faucibus sed. Praesent libero lacus, viverra ac sem sed, hendrerit vehicula dui. Mauris quis rhoncus felis, dignissim blandit velit. Fusce fringilla, dolor vitae ultrices porta, erat urna dignissim nunc, at tincidunt quam nulla vestibulum lacus. Quisque consequat, mi rutrum pretium scelerisque, risus ipsum blandit magna, non maximus mauris quam ut libero. "
            ;
}
